# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "swift2" do
    
#pod 'AFNetworking', '~> 1.2'
#pod 'BlocksKit', '~> 1.8.2'
#pod 'SVProgressHUD', '~> 0.9'
#pod 'FXKeychain', '~> 1.3.1'
#pod 'Base64nl', '~> 1.1'

end

target "swift2Tests" do

end

