# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

use_frameworks!

pod 'AFNetworking', '~> 2.0'
pod 'CocoaLumberjack'
pod 'SVProgressHUD', '~> 0.9'
pod 'FXKeychain', '~> 1.3.1'
pod 'Realm'
pod 'ObjectMapper'



