# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "sampleYoutubeSDK" do
  platform :ios, '6.0'
  pod 'youtube-ios-player-helper', :git=>'https://github.com/youtube/youtube-ios-player-helper', :commit=>'head'
end


