# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SampleBlocks" do
    
pod 'FXKeychain', '~> 1.3.1'

end

target "SampleBlocksTests" do
 pod 'OCMock', '~> 2.0.1'
end

